version: '3.0'

services:
  converter-db:
    image: postgres:10-alpine
    container_name: converter-db
    ports:
    - "5432:5432"
    volumes:
    - ./pgdata/:/var/lib/postgresql/data
    env_file:
      - postgres.env
    networks:
      - converter

  converter-api:
    container_name: converter-api
    build: .
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - converter-db
    networks:
      - converter

networks:
  converter:
    driver: bridge